[package]
name = "suika-game-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.1.3"
rand = "0.8.5"
screenshots = "0.8.4"
winapi = { version = "0.3.9", features = ["winuser"] }
